services:
   redis: 
     image: redislabs/redismod
     ports:
       - '6379:6379' 
   web:
        build: .
        ports:
            - "8007:8007"
        volumes:
            - .:/code
        depends_on:
            - redis